export * as codeDeploy from './CodeDeploy.js'
export * as iam from './Iam.js'
export { default as Lambda } from './Lambda.js'
// export * as lambda from './Lambda.js'
export * as apiGateway from './ApiGateway.js'
export * as sns from './Sns.js'
export * as s3 from './S3.js'
export * as cloudWatchEvents from './CloudWatchEvents.js'
export * as cloudWatchLogs from './CloudWatchLogs.js'
export * as iot from './Iot.js'
export * as appSync from './AppSyncDataSources.js'
